### ISSUE TITLE
predictor.predict

### ISSUE THREAD

**Issue by austinmw** [OElesin/autogluon-tabular-sagemaker-container#1]
Hi, what's the input format for `predictor.predict()`?

**Comment by OElesin** [comment]
@austinmw, thanks for pointing this out. This is a bug current, and working to fix it.
Currently, the format is CSV with headers, but JSON format seems to be better so as to handle SageMaker Batch Transforms

**Comment by OElesin** [comment]
Please give it a try now, it accepts JSON format.

**Comment by austinmw** [comment]
Thanks! Going to try it now. Any chance you could add an example to the README? By the way really appreciate the work you've done here!

**Comment by austinmw** [comment]
@OElesin Hi, finally got a chance to try this. On `predictor.predict` I'm getting:

```
File "/opt/program/predictor.py", line 85, in transformation
predictions = AutoGluonTabularService.predict(data)
File "/opt/program/predictor.py", line 41, in predict
return cls.model.predict(prediction_data)
AttributeError: 'NoneType' object has no attribute 'predict'
```
Could be misunderstanding the intended use of of `predictor.py`, but looks like `AutoGluonTabularService` doesn't call `load_model` unless pinged. Looks like if I call predict multiple times, occassionally it will throw this error, and other times it will not.

**Comment by OElesin** [comment]
This is the expected behaviour. Hosted SageMaker Endpoint takes care of this by default.
